CREATE TABLE TELEDYNE_INSTRUMENT(
DATE1 DATE,
LOCAL_TIME TIME,
DATE2 DATE,
UTCTIME TIME,
AVAILABLE INT,
DISK_SPACE DECIMAL (10,8),
RCELL_TEMP DECIMAL (10,7),
SO2_PPB DECIMAL(10,9),
TRS_PPB DECIMAL(10,9));